<a href="https://colab.research.google.com/github/naagarjunsa/data-science-portfolio/blob/main/deep-learning/tensors_understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Representation for Neural Networks

Tensor is a container for data - usually numbers, in the context of the tensor, the dimension is called an axis.
 
 Types of tensors

*   Scalars - 0 Dimension Tensors
      - contains only a single number
      - can check # of axes by .ndim
*   Vectors - 1 Dimensional Tensors
      - contains only one axis. 
      - axis is better known by rank
      - dimension can be also be entries in an axis
*   Matrices - 2 Dimensional Tensors
      - has two axes, rows and columns
      




# Attributes of Tensor

* Number of axes - rank - ndim

* Shape - tuple of integers to represent dimension across each axis.

* Data Type - dtype - the data type contained in the tensor

In [1]:
#Scalar 0D Tensors
import numpy as np

scalar = np.array(10)
print("Tensor : ", scalar, "\n Axes : ", scalar.ndim)
print("Shape : ", scalar.shape)
print("Data Type : ", scalar.dtype)


Tensor :  10 
 Axes :  0
Shape :  ()
Data Type :  int64


In [2]:
vector = np.array([1,2,3])

print("Tensor : ", vector, "\n Axes : ", vector.ndim)
print("Shape : ", vector.shape)
print("Data Type : ", vector.dtype)

Tensor :  [1 2 3] 
 Axes :  1
Shape :  (3,)
Data Type :  int64


In [3]:
mat = np.array([[1,2,3],
                [4,5,6],
                [6,7,8]])
print("Tensor : ", mat, "\n Axes : ", mat.ndim)
print("Shape : ", mat.shape)
print("Data Type : ", mat.dtype)

Tensor :  [[1 2 3]
 [4 5 6]
 [6 7 8]] 
 Axes :  2
Shape :  (3, 3)
Data Type :  int64


## Manipulating tensors in Numpy

* Tensor Slicing - you may select between any two indices along each tensor axis
* Sample Axes - axis 0 usually represents the number of samples - the rest of the axes represent that particular object
* Whenever we try to batch the training_data we do it with the axis 0.

In [4]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [5]:
train_images.shape

(60000, 28, 28)

In [6]:
train_images[:,:,:].shape

(60000, 28, 28)

In [7]:
train_images[:256,:,:].shape

(256, 28, 28)

# Types of Tensor Data : 

- Vector data — 2D tensors of shape (samples, features)
each single data point can be encoded
as a vector
-  Timeseries data or sequence data — 3D tensors of shape (samples, timesteps,
features) 
each sample is a journey of one data point features across many timesteps.
each single data point can be encoded as a matrix.
- Images — 4D tensors of shape (samples,
 height, width, channels)
each single data point can be encoded as a 3d tensor.
- Video — 5D tensors of shape
(samples, frames, height, width, channels)

In [16]:
z = np.maximum(x, 0)
z

array([[0.27617087, 0.0805324 , 0.86980492, ..., 0.39256523, 0.34371401,
        0.62863402],
       [0.48766359, 0.39327852, 0.62805067, ..., 0.99588684, 0.37521751,
        0.30944731],
       [0.02664074, 0.2914958 , 0.97697369, ..., 0.89988097, 0.67009451,
        0.53760595],
       ...,
       [0.11554085, 0.7826905 , 0.28861266, ..., 0.01190161, 0.91694084,
        0.11565993],
       [0.93355627, 0.03236113, 0.06205642, ..., 0.43667554, 0.04381913,
        0.92493927],
       [0.78535486, 0.04958228, 0.7467012 , ..., 0.4795967 , 0.69161645,
        0.80287611]])